// Generated by create-wx-app
#include "application.h"
#include "mainframe.h"

bool Application::OnInit() {
    if(!wxApp::OnInit()) {
        return false;

    }

    auto mainFrame = new MainFrame();
    mainFrame->Show();

    return true;
}

wxIMPLEMENT_APP(Application);
