// Generated by create-wx-app
#include "mainframe.h"

MainFrame::MainFrame()
    : wxFrame(nullptr,
              wxID_ANY,
              "Hello World",
              wxDefaultPosition,
              wxSize(800, 600)) {
    //
}
